---
title: "M2->M1 transactivation"
author: "Tim D. Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{M1->M2 transactivation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r message=FALSE}
library(FlowAnalysis)
library(magrittr)
library(dplyr)
library(ggplot2)
names(m2_m1)
names(m2_sus_m1)
```

## 2D density plots

### Wash-out
```{r}
m2_m1 %>% filter(antibody=="exp") %>% render_density_plots()
```

### M2 sustained
```{r}
m2_sus_m1 %>% filter(antibody=="exp") %>% render_density_plots()
```

## Median plots

### Wash-out
For each experiment:
```{r}
m2_m1_medians = make_medians(m2_m1)
render_median_plots(m2_m1_medians)
```

Summarized:
```{r}
normalized_m2_m1 = normalize_by_positive_controls(m2_m1)
normalized_m2_m1_medians = make_medians(normalized_m2_m1)
render_summary_median_plots(normalized_m2_m1_medians)
```

### M2 sustained
For each experiment:
```{r}
m2_sus_m1_medians = make_medians(m2_sus_m1)
render_median_plots(m2_sus_m1_medians)
```

Summarized:
```{r}
normalized_m2_sus_m1 = normalize_by_positive_controls(m2_sus_m1)
normalized_m2_sus_m1_medians = make_medians(normalized_m2_sus_m1)
render_summary_median_plots(normalized_m2_sus_m1_medians)
```
